project_id = "hrbubonlmtwdkfrblwin"

[functions.chat]
verify_jwt = false

[functions.manage-api-key]
verify_jwt = false

[functions.generate-prompt]
verify_jwt = false

[functions.execute-prompt]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.image-to-prompt]
verify_jwt = false

[functions.crypto-prices]
verify_jwt = false
